### PR TITLE
Wp43 compat

### PR DESCRIPTION
**Pull request by kidfiction**
Whitespace and Copyright update included

### CODE REVIEW

**Comment by tpolischuk** [comment]
Did this merge make Annotum compatible with the latest version of WordPress? @kidfiction

**Comment by carlthewebmaster** [comment]
Yes.

**Comment by tpolischuk** [comment]
Yes! @kidfiction @carlthewebmaster You guys rock.

**Comment by carlthewebmaster** [comment]
Download the updated Annotum 2.1 theme from
https://github.com/Annotum/Annotum/releases/download/v2.1/annotum-base.zip

**Pull request merged**
